package demg2.prog2;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class dj implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Boolean anme;
   private int roll;
   private java.lang.String oyt;

   public dj()
   {
   }

   public java.lang.Boolean getAnme()
   {
      return this.anme;
   }

   public void setAnme(java.lang.Boolean anme)
   {
      this.anme = anme;
   }

   public int getRoll()
   {
      return this.roll;
   }

   public void setRoll(int roll)
   {
      this.roll = roll;
   }

   public java.lang.String getOyt()
   {
      return this.oyt;
   }

   public void setOyt(java.lang.String oyt)
   {
      this.oyt = oyt;
   }

   public dj(java.lang.Boolean anme, int roll, java.lang.String oyt)
   {
      this.anme = anme;
      this.roll = roll;
      this.oyt = oyt;
   }

}